apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api-development
  namespace: development
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: MESSAGE
              value: "hello world development namespace"
