apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
    spec:
      containers:
      - name: api
        image: nmatsui/hello-world-api  # Default image
        ports:
        - containerPort: 8080
